version: '3.5'

services:
  api:
    build: 
      context: "server"
      dockerfile: "Dockerfile"
    ports:
      - 8080:3000
    networks:
      - backend
    restart: always
networks:
    backend:
        driver: bridge      
